### PR TITLE
Minor Chem Fixes

### LINKED ISSUE #63: LiBF4 -> LiH + BF3
### GregTech CEu Version

v2.4.0

### Gregicality Multiblocks Version

v1.1.4

### Gregicality Science Version

v0.0.1

### Modpack Used

GregTech Expert 2

### Addons Installed

_No response_

### Environment

SP

### New Worlds

Yes

### Cross-Mod Interaction

No

### Expected Behavior

LiBF4 -> LiF + BF3

### Actual Behavior

LiBF4 -> LiH + BF3
Where does Hydrogen comes from
https://github.com/GregTechCEu/gregicality-science/blob/d727de61248dd4d018a80747acff68ae91423f40/src/main/java/gregicality/science/loaders/recipe/chain/BoronNitrideChain.java#L73

### Steps to Reproduce

this is a recipe bug

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by pablocnvs**
Fixes #63 , #61 , #59  , #58, as well as inconsistencies with the handling of Ammonium Chloride

PS: this time i had the local repo properly synced up, so no weird incompatibiities when merging (hopefully)

### CODE REVIEW

**Comment by Irgendwer01** [comment]
@pablocnvs Why did you created a new PR?

**Comment by pablocnvs** [comment]
Because apparently i didn't update the repo in my laptop, so when i got to making the pr i saw there were merge conflicts. i hadn't used github for a while and i was a bit rusty, so i went for the rather lengthy process of redoing the pr.

File: src/main/java/gregicality/science/api/unification/materials/GCYSFirstDegreeMaterials.java [hunk 1]
```diff
@@ -962,5 +962,11 @@ public static void init() {
                 .iconSet(MaterialIconSet.SHINY)
                 .components(Magnesium, 1)
                 .build();
+
+        LithiumFluoride = new Material.Builder(3628,"lithium_fluoride")
+                .dust()
+                .color(LithiumHydride.getMaterialRGB())
```
Comment (TechLord22) [inline src/main/java/gregicality/science/api/unification/materials/GCYSFirstDegreeMaterials.java:968]: It'd be better to give this its own unique color.

**Review by TechLord22 — CHANGES_REQUESTED** [review]

**Review by TechLord22 — APPROVED** [review]
